### ISSUE TITLE
关于训练和测试

### ISSUE THREAD

**Issue by mengxzh15** [shallowdream204/SODA-SR#3]
可以在readme里介绍一下你的环境配置、数据的路径、训练和测试步骤吗?像其他作者一样，介绍一下。
train.py和test.py分别放在哪里，需要找好久哩。

**Comment by mengxzh15** [comment]
略微有些乱，一个文件下有太多用不到文件。希望能够整理一下。谢谢。

**Comment by shallowdream204** [comment]
Thank you for your interest in our paper and for your reminder.
This repo has the same structure as  [KAIR](https://github.com/cszn/KAIR).  Currently, I am occupied with other projects and may not have the time to update this repository at this moment. I'll reorganize this repo as soon as possible. I apologize for any inconvenience this may cause.
