### ISSUE TITLE
训练顺序

### ISSUE THREAD

**Issue by mengxzh15** [shallowdream204/SODA-SR#5]
补充材料收到了，非常感谢。我自己刚刚接触SR这方面的研究，对KAIR并不熟悉。根据您文章的介绍，先训练教师网络，再训练学生网络。那么，这三个文件main_train_sodasr.py、main_train_psnr.py、main_train_gan.py，是先训练main_train_psnr.py(教师网络），再训练main_train_sodasr.py呢，或者是其他的组合？

麻烦百忙之中回复一下，非常感谢。

**Comment by ZaizuoTang** [comment]
> 补充材料收到了，非常感谢。我自己刚刚接触SR这方面的研究，对KAIR并不熟悉。根据您文章的介绍，先训练教师网络，再训练学生网络。那么，这三个文件main_train_sodasr.py、main_train_psnr.py、main_train_gan.py，是先训练main_train_psnr.py(教师网络），再训练main_train_sodasr.py呢，或者是其他的组合？
> 
> 麻烦百忙之中回复一下，非常感谢。

请问您现在解决了这个问题了吗？是应该执行main_train_sodasr.py加上swinir/train_soda_sr_classical.json进行域自适应训练吗？
