### ISSUE TITLE
代码错误

### ISSUE THREAD

**Issue by mengxzh15** [shallowdream204/SODA-SR#8]
![image](https://github.com/user-attachments/assets/bd53154f-59aa-431c-b0aa-ab01e70e864e)
没有这个module，大佬是不是没有把代码完全上传完呀。求更新并整理代码

**Comment by shallowdream204** [comment]
This is PyTorch DDP model.module

**Comment by mengxzh15** [comment]
DDP is Distributed Data Parallel?
