### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by ZaizuoTang** [shallowdream204/SODA-SR#9]
When I directly utilize the pre trained weights of the open-source SwinIR (001_classicalSR_DIV2K_s48w8_SwinIR-M_x4.pth) to perform domain adaptive training (main_train_sodasr.py，options/swinir/train_soda_sr_classical.json)， The following issues may occur:

 Traceback (most recent call last):
  File "/home/tzz/Work_file/CODE/SODA/SODA-SR-main/train_test_scripts/main_train_sodasr.py", line 299, in <module>
    main()
  File "/home/tzz/Work_file/CODE/SODA/SODA-SR-main/train_test_scripts/main_train_sodasr.py", line 229, in main
    model.optimize_parameters(current_step,confidence)
  File "/home/tzz/Work_file/CODE/SODA/SODA-SR-main/./models/model_plain.py", line 173, in optimize_parameters
    G_loss.backward()
  File "/home/tzz/anaconda3/envs/hat/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/tzz/anaconda3/envs/hat/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [8, 3, 3, 180]], which is output 0 of AsStridedBackward0, is at version 2; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

Could the author please help solve this problem? Thank you very much!

**Comment by codeslake** [comment]
> When I directly utilize the pre trained weights of the open-source SwinIR (001_classicalSR_DIV2K_s48w8_SwinIR-M_x4.pth) to perform domain adaptive training (main_train_sodasr.py，options/swinir/train_soda_sr_classical.json)， The following issues may occur:
> 
> Traceback (most recent call last): File "/home/tzz/Work_file/CODE/SODA/SODA-SR-main/train_test_scripts/main_train_sodasr.py", line 299, in main() File "/home/tzz/Work_file/CODE/SODA/SODA-SR-main/train_test_scripts/main_train_sodasr.py", line 229, in main model.optimize_parameters(current_step,confidence) File "/home/tzz/Work_file/CODE/SODA/SODA-SR-main/./models/model_plain.py", line 173, in optimize_parameters G_loss.backward() File "/home/tzz/anaconda3/envs/hat/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward torch.autograd.backward( File "/home/tzz/anaconda3/envs/hat/lib/python3.10/site-packages/torch/autograd/**init**.py", line 200, in backward Variable._execution_engine.run_backward( # Calls into the C++ engine to run the backward pass RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [8, 3, 3, 180]], which is output 0 of AsStridedBackward0, is at version 2; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
> 
> Could the author please help solve this problem? Thank you very much!

Hey, @ZaizuoTang , I've encountered the same problem and found that the root cause stems from [this line](https://github.com/shallowdream204/SODA-SR/blob/main/models/network_soda.py#L870). `self.level_embed` can contain `nan` value without an initialization. I've applied `xavier_uniform_` to `self.level_embed` and fixed the problem (i.e., `from torch.nn.init import xavier_uniform_; xavier_uniform_(self.level_embed`)).
